apiVersion: storageos.com/v1
kind: StorageOSCluster
metadata:
  name: example-storageoscluster
  namespace: "default"
spec:
  secretRefName: "storageos-api"
  secretRefNamespace: "default"
  namespace: "storageos"
  # k8sDistro: openshift
  # tlsEtcdSecretRefName:
  # tlsEtcdSecretRefNamespace:
  # disableTelemetry: true
  # images:
  #   nodeContainer:
  #   initContainer:
  #   csiNodeDriverRegistrarContainer:
  #   csiClusterDriverRegistrarContainer:
  #   csiExternalProvisionerContainer:
  #   csiExternalAttacherContainer:
  #   csiLivenessProbeContainer:
  #   hyperkubeContainer:
  csi:
    enable: true
  #   endpoint: /var/lib/kubelet/device-plugins/
  #   registrarSocketDir: /var/lib/kubelet/device-plugins/
  #   kubeletDir: /var/lib/kubelet
  #   pluginDir: /var/lib/kubelet/plugins/storageos/
  #   deviceDir: /dev
  #   registrationDir: /var/lib/kubelet/plugins
  #   enableProvisionCreds: false
  #   enableControllerPublishCreds: false
  #   enableNodePublishCreds: false
  #   kubeletRegistrationPath: /var/lib/kubelet/plugins/storageos/csi.sock
  #   driverRegisterationMode: node-register
  #   DriverRequiresAttachment: "true"
  #   deploymentStrategy: "deployment"
  # service:
  #   name: "storageos"
  #   type: "ClusterIP"
  #   externalPort: 5705
  #   internalPort: 5705
  #   annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443"
  # ingress:
  #   enable: false
  #   hostname: storageos.local
  #   tls: false
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #     kubernetes.io/tls-acme: true
  # sharedDir should be set if running kubelet in a container.  This should
  # be the path shared into to kubelet container, typically:
  # "/var/lib/kubelet/plugins/kubernetes.io~storageos".  If not set, defaults
  # will be used.
  # sharedDir:
  # kvBackend:
  #   address:
  #   backend:
  # nodeSelectorTerms:
  #   - matchExpressions:
  #     - key: somekey
  #       operator: In
  #       values:
  #       - nodefoo
  # tolerations:
  #   - key: somekey
  #     operator: "Equal"
  #     value: nodefoo
  #     effect: "NoSchedule"
  # resources:
  #   limits:
  #     memory: "1Gi"
  #   requests:
  #     memory: "702Mi"
  # disableFencing: false
  # disableTCMU: false
  # forceTCMU: false
  # disableScheduler: false

---
apiVersion: v1
kind: Secret
metadata:
  name: "storageos-api"
  namespace: "default"
  labels:
    app: "storageos"
type: "kubernetes.io/storageos"
data:
  # echo -n '<secret>' | base64
  apiUsername: c3RvcmFnZW9z
  apiPassword: c3RvcmFnZW9z
  # Add base64 encoded TLS cert and key below if ingress.tls is set to true.
  # tls.crt:
  # tls.key:
  # Add base64 encoded creds below for CSI credentials.
  # csiProvisionUsername:
  # csiProvisionPassword:
  # csiControllerPublishUsername:
  # csiControllerPublishPassword:
  # csiNodePublishUsername:
  # csiNodePublishPassword:
