apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-cluster-operator
  namespace: storageos-operator
  labels:
    app.kubernetes.io/name: storageos-operator
    app.kubernetes.io/instance: storageos-cluster-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: storageos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storageos-cluster-operator
  template:
    metadata:
      labels:
        name: storageos-cluster-operator
    spec:
      serviceAccountName: storageoscluster-operator-sa
      containers:
        - name: storageos-cluster-operator
          image: storageos/cluster-operator:test
          ports:
          - containerPort: 8383
            name: metrics
          - containerPort: 8686
            name: operatormetrics
          - containerPort: 5720
            name: podschedwebhook
          command:
          - cluster-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: RELATED_IMAGE_STORAGEOS_NODE
              value: ""
            - name: RELATED_IMAGE_STORAGEOS_INIT
              value: ""
            - name: RELATED_IMAGE_CSIV1_CLUSTER_DRIVER_REGISTRAR
              value: ""
            - name: RELATED_IMAGE_CSIV1_NODE_DRIVER_REGISTRAR
              value: ""
            - name: RELATED_IMAGE_CSIV1_EXTERNAL_PROVISIONER
              value: ""
            - name: RELATED_IMAGE_CSIV1_EXTERNAL_ATTACHER
              value: ""
            - name: RELATED_IMAGE_CSIV1_EXTERNAL_ATTACHER_V2
              value: ""
            - name: RELATED_IMAGE_CSIV1_LIVENESS_PROBE
              value: ""
            - name: RELATED_IMAGE_CSIV0_DRIVER_REGISTRAR
              value: ""
            - name: RELATED_IMAGE_CSIV0_EXTERNAL_PROVISIONER
              value: ""
            - name: RELATED_IMAGE_CSIV0_EXTERNAL_ATTACHER
              value: ""
            - name: RELATED_IMAGE_NFS
              value: ""
            - name: RELATED_IMAGE_KUBE_SCHEDULER
              value: ""
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "storageos-cluster-operator"
            - name: DISABLE_SCHEDULER_WEBHOOK
              value: "false"
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule" 
