apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageos-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: storageos-operator
  template:
    metadata:
      labels:
        name: storageos-operator
    spec:
      containers:
        - name: storageos-operator
          image: storageos/operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - storageos-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "storageos-operator"
